### ISSUE TITLE
Add the ability to ignore domains

### ISSUE THREAD

**Issue by kargig** [ehloonion/onionrouter#10]
There are cases where we don't want onionrouter to decide on what will happen for a specific domain. Such a case is when there's another transport defined, e.g. in some other file/transport_map, for a domain, so we would like onionrouter to reply with '500' for these domains, even if they have an onion-mx SRV record set, so that postfix will fall back to the other transport defined.

It's very probable that there could be multiple such domains, so the new option should accept a comma separated list of domains.

I'm proposing 'ignore_domains' as the key name for such an option.

**Comment by micah** [comment]
George Kargiotakis <notifications@github.com> writes:

> It's very probable that there could be multiple such domains, so the new option should accept a comma separated list of domains.

If its quite a few, a comma separated list could get annoyingly
long. Maybe newline separation is better?

> I'm proposing 'ignore_domains' as the key name for such an option.

sounds good to me

**Comment by ioparaskev** [comment]
I think the comma separator is something we should keep because spaces and newlines are not always consistent and are usually dependent on screen size, taste etc. Keeping the comma separator allows easier to spot separation while at the same time allowing multi-line values. I can add this to the documentation (not sure if it will help or confuse though).

In any case, current implementation of #11 supports multiple lines as well. The following
````
[IGNORED]
domains: ignore3.me, ignore2.me,
         ignore.me
````
is the same as this:
````
[IGNORED]
domains: ignore3.me, ignore2.me, ignore.me
````
